# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinBa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'AlamofireObjectMapper', '~> 4.0'
	pod ‘RxSwift’
	pod ‘Kingfisher’
	pod ‘RxAlamofire’
	pod 'Cosmos', '~> 8.0'

  # Pods for LinBa

  target 'LinBaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LinBaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
